function onCreatePost()
	makeLuaSprite('whitebg', '', 0, 0)
	setScrollFactor('whitebg', 0, 0)
	makeGraphic('whitebg', 3840, 2160, 'ffffff')
	addLuaSprite('whitebg', false)
	setProperty('whitebg.alpha', 0)
	screenCenter('whitebg', 'xy')
end
function onEvent(n, v1, v2)
	if n == 'badapplelol' and string.lower(v1) == 'a' then
		doTweenAlpha('applebadxd69', 'whitebg', 1, v2, 'linear')
		doTweenColor('badapplexd', 'boyfriend', '000000', v2, 'linear')
		doTweenColor('badapplexd1', 'dad', '000000', v2, 'linear')
		doTweenColor('badapplexd2', 'gf', '000000', v2, 'linear')
		--doTweenColor('badapplexd6', 'healthBar', '000000', v2, 'linear')
		doTweenColor('badapplexd200', 'limo', '000000', v2, 'linear')
		--doTweenColor('badapplexd100', 'iconP1', '000000', v2, 'linear')
		--doTweenColor('badapplexd10', 'iconP2', '000000', v2, 'linear')
		doTweenAlpha('badapplexd109', 'timeBarBG', 0, v2, 'linear' )
		doTweenAlpha('badapplexd110', 'timeBar', 0, v2, 'linear')
		--doTweenAlpha('badapplexd111', 'timeBar', 0, v2, 'linear')
		doTweenAlpha('badapplexd111', 'timeTxt', 0, v2, 'linear')
		doTweenAlpha('badapplexd104', 'scoreTxt', 0, v2, 'linear')
		doTweenAlpha('badapplexd112', 'healthBarBG', 0, v2, 'linear')
		doTweenAlpha('badapplexd113', 'healthBar', 0, v2, 'linear')
		doTweenAlpha('badapplexd114', 'iconP2', 0, v2, 'linear')
		doTweenAlpha('badapplexd115', 'iconP1', 0, v2, 'linear')
	end
	if n == 'badapplelol' and string.lower(v1) == 'b' then
		doTweenAlpha('applebadxd', 'whitebg', 0, v2, 'linear')
		doTweenColor('badapplexd3', 'boyfriend', 'FFFFFF', v2, 'linear')
		doTweenColor('badapplexd4', 'dad', 'FFFFFF', v2, 'linear')
		doTweenColor('badapplexd5', 'gf', 'FFFFFF', v2, 'linear')
		doTweenColor('badapplexd201', 'limo', 'FFFFFF', v2, 'linear')
		--doTweenColor('badapplexd7', 'healthBar', 'FFFFFF', v2, 'linear')
		--doTweenColor('badapplexd101', 'iconP1', 'FFFFFF', v2, 'linear')
		--doTweenColor('badapplexd11', 'iconP2', 'FFFFFF', v2, 'linear')
		doTweenAlpha('badapplexd102', 'timeBarBG', 1, v2, 'linear' )
		doTweenAlpha('badapplexd103', 'timeBar', 1, v2, 'linear')
		--doTweenAlpha('badapplexd104', 'timeBar', 1, v2, 'linear')
		doTweenAlpha('badapplexd104', 'timeTxt', 1, v2, 'linear')
		doTweenAlpha('badapplexd116', 'scoreTxt', 1, v2, 'linear')
		doTweenAlpha('badapplexd105', 'healthBarBG', 1, v2, 'linear')
		doTweenAlpha('badapplexd106', 'healthBar', 1, v2, 'linear')
		doTweenAlpha('badapplexd107', 'iconP2', 1, v2, 'linear')
		doTweenAlpha('badapplexd108', 'iconP1', 1, v2, 'linear')
	end
end